Logo + Stealth Mode
daasl/www.daasl.io pull request #13
Opened 2020-11-19 19:44 UTC by ian-bloom

2020-11-19 22:41 UTC, SteveHenley requested changes
The logo looks good.  I am thinking that the text would look better center justified?  What are your thoughts?  Could we give it a try and see what it looks like?

2020-11-20 18:11 UTC, ian-bloom commented
> The logo looks good. I am thinking that the text would look better center justified? What are your thoughts? Could we give it a try and see what it looks like?

The point of mocking up the page in GH Markdown is so that we can easily collaborate around building content. 
GitHub Markdown does not have an easy way to center elements. You'd have to use HTML and styling (like we did with the logo). This makes collaboration and building content more difficult.

I think we should stick to Markdown as much as possible until it is necessary to add styling for a more elaborate webpage.

```

2020-11-21 02:13 UTC, SteveHenley commented
Sounds reasonable to me.  Let's go with what you have.

2020-11-21 02:13 UTC, SteveHenley approved these changes

2020-12-03 19:38 UTC, merged